### ISSUE TITLE
first start

### ISSUE THREAD

**Issue by CCCCarsten** [andune/HomeSpawnPlus#100]
Hi,

just downloaded the plugin and put it into plugin folder. Once after restarting the Server I have got this error:

http://pastebin.com/psQQ0Nwj

Ciao, Carsten

**Comment by CCCCarsten** [comment]
Plugin.yml --> set database to false does not help. Another error then but error :)

**Comment by sorifiend** [comment]
Hi, if you scroll down that error log you will see

`Caused by: java.sql.SQLException: Access denied for user 'ni123456_1_DB'@'127.0.0.1' (using password: YES)`

Are you certain your username and password is correct? Can you log into it manually from the database console?

Also do not touch the plugin.yml like that. If you don't want to use a database the edit the config.yml instead, and find the setting to save to file rather that to your database, from memory I think its near the top of the config.

**Comment by CCCCarsten** [comment]
I have to apologize. Thousands of plugins don't require the **bukkit.yml** to configure the SQL database. But HomeSpawnPlus already :). I did not know that. I can work with HSP now :)). Thank you very much!
