### ISSUE TITLE
SQL error 

### ISSUE THREAD

**Issue by CCCCarsten** [andune/HomeSpawnPlus#109]
Hi,

approximately every two days I get this error in my server console:
http://pastebin.com/LTXtWP01

I am not specialist, but it seems that HSP has lost the connection to my SQL database, which is provided by Nitrado.de (like the server). It is my impression that HSP don't "autoconnect" to SQL ( -autoconnect ).

Ciao, Carsten

**Comment by andune** [comment]
Agreed this looks like an issue with connectivity to the database, perhaps it was being restarted regularly. HSP depends on Ebeans for its DB connection and it seems Ebeans is throwing an exception when the DB connection disappears. This is probably correct behavior. Ideally it automatically reconnects when the database returns.
If you are still having or believe this issue is related to something other that DB restarts, feel free to re-open and provide additional details on the issue.
