### ISSUE TITLE
DeleteHome other

### ISSUE THREAD

**Issue by Kloporte** [andune/HomeSpawnPlus#31]
Hi It would be handy to have a command  for deleting the house of an another player (in my case, to delete house of non returning players) with : 

/homeotherdelete <player>

**Comment by andune** [comment]
This has been part of HSP for a long time, since 1.5 or so I think.

https://github.com/andune/HomeSpawnPlus/blob/master/core/src/main/java/com/andune/minecraft/hsp/commands/HomeDeleteOther.java#L47

Various aliases you can use:

/home do <player>
/hdo <player>
/homedeleteother <player>    # if you like typing

You can also delete namedHomes:

/hdo <player> <homeName>

Or target the default home on a specific world:

/hdo <player> <w:theWorld>

Sadly, I see the reason you are asking is because this command isn't mentioned in the documentation at all, which only underscores the sad state of the documentation compared with the code. HSP has features (such as teleport effects) that aren't documented at all. I have plans to move the documentation to the wiki here on github and will take advantage of the opportunity to update it at that time.

The new uber commands are somewhat a help as you can at least see this if you just run "/home help" - you will see "deleteother" in the subcommand list.

**Comment by andune** [comment]
Also because of the generally sad state of the online documentation at this time, your best source for what commands are available is the code itself:

https://github.com/andune/HomeSpawnPlus/tree/master/core/src/main/java/com/andune/minecraft/hsp/commands

Although, as mentioned, HSP 2.0 now has uber commands, which neatly group all of hsp commands under one of three easy-to-remember uber commands:  /home, /spawn and /hsp. Running any of those three with sub-command "help" will show you all possible other HSP commands that you have access to. Make sure you've setup your "hsp.*" permission as an admin so you can see all of the commands.
