### ISSUE TITLE
HSP throws exception on start up

### ISSUE THREAD

**Issue by Xibalba** [andune/HomeSpawnPlus#40]
This is what happens when I start my server with HSP 2.0 build 610 or build 615 : http://pastebin.com/9CZD63hN

It works works fine with build 606.

**Comment by andune** [comment]
Ah. This is because of the auto-UUID cleanup I built in for servers that had players with duplicate records as a result of UUID/name changes. You can disable the auto-cleanup by adding the config **core.uuidCleanupOnStartup: false**.

HSP will automatically migrate name changes when it sees them; this uuid cleanup is only for servers that had people login with a name change prior to the built in HSP auto-migration. So if you don't have that situation, add this config and you're good to go.

If you do have that situation, then I will either have to code a few extra routines for YAML so the auto-purge can work for you, or since it's YAML, if your data file is small enough you can always just edit the file to fix the data also.

**Comment by andune** [comment]
Can you confirm the configuration change fixed the problem?

**Comment by Xibalba** [comment]
Sorry I just got my hands on it today, but I can confirm that it works with build 618 ;)
