### ISSUE TITLE
Plugin stopped working, plz help !

### ISSUE THREAD

**Issue by mcmyster** [andune/HomeSpawnPlus#41]
Last night i was on my 24/7 server hosted by MCprohosting and hsp was working fine, i got on this morning and i done /spawn and it was back to essentials spawn plugin, hsp wast on the /plugins list so i deleted the config and reloaded, still nothing , so i re-downloaded hsp and turned on my server still nothing, PLEASE HELP ME

**Comment by andune** [comment]
HSP 2.0 has a built-in module that detects Essentials and does some internal twiddling of Essentials internal "command override" system, since Essentials can't see HSP's dynamic commands. This integration is highly sensitive to Essentials internal implementation, so if that changes at some point (and maybe it already has since I last tested it), I'd have to update it. I wrote it because the number 1 issue I had reported was problems with Essentials, despite it being the first question on the [FAQ](http://dev.bukkit.org/bukkit-plugins/homespawnplus/pages/faq/).

If the automatic mechanism isn't of HSP isn't working, you'll have to fall back to the mechanism noted in the FAQ of remapping your [command conflicts](http://dev.bukkit.org/bukkit-plugins/homespawnplus/pages/command-conflicts/). That will solve your problem permanently, regardless of how you upgrade (you don't have to rename JARs or edit plugin.yml's). And if you ever decide to remove HSP, then you just remove the aliases.
