### ISSUE TITLE
Costs for home invites?

### ISSUE THREAD

**Issue by D3v3l0per** [andune/HomeSpawnPlus#42]
Hi,

I've been trying to solve a little problem but haven't really found any solution to that so far...:
I can't set the costs for home invites in economy.yml.

I added "homeinvite: 50" under the category "cost". 
Although I set the costs to 50, no money is taken from my account.
Here's my economy.yml: http://pastebin.com/uhMQYMiK

I'm using HSP build #615 (the newest) and Vault 1.5.2.

Thanks in advance!

**Comment by andune** [comment]
Are you admin with all permissions? If so, you have the hsp.CostExempt.* permission and no money will be taken from your account.

**Comment by D3v3l0per** [comment]
I have also tried it without OP...it didn't seem to work.

**Comment by andune** [comment]
Turns out this was caused by the addition of a new config in HSP 2.0 "cost.enabled", which was added so admins could enable/disable HSP economy functionality with a single boolean value. Unfortunately I never added it to the default configs, so it was defaulting to false. Simple fix:

```
# economy.yml
cost:
  enabled: true
```

Or you can also download the latest build off of Jenkins which has this set to true in the default configs.
