### ISSUE TITLE
/spawn and /home not working on Cauldron server - Caught exception in command 

### ISSUE THREAD

**Issue by rustyshakelford2** [andune/HomeSpawnPlus#67]
I'm trying to use HomeSpawnPlus on my cauldron server, and it's throwing this error any time you try to /spawn or /home. 

http://pastebin.com/h5tmRqeV

**Comment by andune** [comment]
Set **core.safeTeleport** to false in core.yml. The safe teleport algorithms were written for Bukkit and likely don't take into account extra blocks that cauldron might be using.

**Comment by rustyshakelford2** [comment]
I have 'safeTeleport: false' in core.yml but that doesn't seem to stop the error. I've tried the most recent build 631 on jenkins as well as 2.0 on bukkitdev.

**Comment by phani00** [comment]
me too, same error, same situation. strange thing is that it used to work until i recreated my worlds. disabled all mod's that have been added recently, still no luck. has me puzzled why it used to work w/o errors but decided to throw them now...

**Comment by andune** [comment]
I believe this is a bug that was fixed in 1.7 thanks to a pull request from @zhro, which I failed to pull forward into the 2.0 code base. I have merged the changes @zhro made in 1.7 into the 2.0 teleport code and a new build (#632) is up on Jenkins with these changes which I believe will resolve this issue. Please test and report back.

**Comment by phani00** [comment]
works great, thank you!

**Comment by rustyshakelford2** [comment]
All fixed! Thanks for the quick update. No issues at all on cauldron/kcauldron now.
