### ISSUE TITLE
Question about /setspawn <name of spawn>

### ISSUE THREAD

**Issue by JohOply** [andune/HomeSpawnPlus#68]
Hi

I want to create a special spawn when a player die in a particular region. I want to use a named spawn, but the server ask to me put a player name...

I saw that : "setspawn <name>	Create a named spawn on the local world. This does not become the default spawn or overwrite the map spawn	hsp.command.setspawn.named"

Could you explain to me how that work please ?

EDIT: I don't understand... I have 2 servers. For one, that's work, for another, that say me "no players matched query"

**Comment by andune** [comment]
I'm not entirely sure I understand the problem as it relates to the goal you described.

You say region: define region? Is this a WorldGuard/WorldEdit region? If so, consider using Worldguard's built-in region spawn and let HSP defer to it (spawnWorldGuardRegion). If by region you mean a specific world, then you can use per-world spawns.

Separately, in case the information helps your situation, HSP allows named spawns, such as "/setspawn foo". If a player has the appropriate permission, as you note, they could then type "/spawn foo" in order to be sent to that spawn. You could choose not to give them the permission but instead use a command-block to force them to that spawn, so they could only do it by clicking on the command block. You also could build that spawn into a strategy of your choosing using **spawnNamedSpawn:foo**, so from this you could build custom commands, or set it so players spawn there only when they have a certain permission or are on a certain world, etc.

**Comment by JohOply** [comment]
I'm sorry, english isn't my native language and i havn't any time before to try to find the problem :(

Yes, i speak about a WG/WE region which is in a world which have different rules about spawn (so i can't use per world option).

And finally i just find the problem for now : i forget to configure Commandbook, which manages spawns, and he seems has the priority. 

In all cases, thanks for your help and your assistance :)
