### ISSUE TITLE
Very bad timings and low tps caused by BukkitEventDispatcher::onPlayerQuit(PlayerQuitEvent) 

### ISSUE THREAD

**Issue by Okane84** [andune/HomeSpawnPlus#74]
Hi, here are the timings: 
http://timings.aikar.co/?url=11850422 
http://timings.aikar.co/?url=11850394
http://timings.aikar.co/?url=11850300
http://timings.aikar.co/?url=11850149
http://timings.aikar.co/?url=11850056
I'm really trying everything but no solution. 
Updated from 1.8.6 spigot to 1.8.7 spigot and rolled back thinking that was the problem.
Please help, the server it is very unstable and unplayable, keeps crashing.

**Comment by Okane84** [comment]
http://timings.aikar.co/?url=11851355

:( i tried also latest versions of hsp, no results. I don't know why this is changed so bad, i tried an update of both spigot from 1.8.6 to lastest 1.8.7 and hsp to latest dev build, then rolled back when the problem come out, but it never came to work as it was before :\

**Comment by andune** [comment]
The two methods with bad timings are onPlayerKick and onPlayerQuit, they both call the same common method:

https://github.com/andune/HomeSpawnPlus/blob/master/core/src/main/java/com/andune/minecraft/hsp/util/SpawnUtil.java#L273

Two things are happening in this method: it's looking up the player object, usually very fast because it's a read operation and the underlying mechanics for both EBEANS and YAML operate similar in that they cache data for reads. The second thing is it is writing out: in YAML in particular, I've seen write operations sometimes take a long time. If you're using an external MySQL database, that's possibly a culprit also.

The easy test for both of these, as you can see from the code, is to disable RecordLastLogoutLocation in the config file (**core.recordLastLogout: false**). Changing that setting should fix whatever lag you are seeing because at that point, kick/quit are practically equivalent to a NO-OP for HSP.

**Comment by Okane84** [comment]
Will Disabling the record last location make players rejoin at their home instead of their last location?

**Comment by Okane84** [comment]
Setting to false solved the issue. Thank you man.
